<?= $this->doctype() ?>

<html lang="en">
    <head>
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/img/favicon.ico'])
                ->prependStylesheet($this->basePath('/public/css/style.css'))
                ->prependStylesheet($this->basePath('/public/css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('/public/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('/public/js/bootstrap.min.js'))
                ->prependFile($this->basePath('/public/js/jquery-3.3.1.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('inicio') ?>">
                        <img src="<?= $this->basePath('/public/img/zf-logo.png') ?>" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('inicio') ?>">Home</a></li>

                        <li><a href="<?= $this->url('catalogo') ?>">Catalogo</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        <?php if ($this->layout()->auth->isLoggedIn()): ?>
                            <div class="collapse navbar-collapse">
                                <?php //echo $this->navigation('navi')->menu()->setUlClass('nav navbar-nav'); ?>
                            </div>
                                                       <li class="dropdown">
                                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                                                Bienvenido <?= $this->layout()->auth->getIdentity()->nombre ?> <span class="caret"></span>
                                                            </a>
                                                            <ul class="dropdown-menu" role="menu">
                                                                <li><a href="<?= $this->url('login', ['action' => 'success']) ?>">Perfil</a></li>
                                                                <li><a href="<?= $this->url('login', ['action' => 'logout']) ?>">Logout</a></li>
                                                            </ul>
                                                        </li>

                        <?php else: ?>
                            <li><a href="<?= $this->url('login') ?>">Login</a></li>

                        <?php endif; ?>


                    </ul>
                </div>
            </div>
        </nav>

        <?= $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger')) ?>
        <?= $this->flashMessenger()->render('info', array('alert', 'alert-dismissible', 'alert-info')) ?>
        <?= $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')) ?>
        <?= $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success')) ?>

        <div class="container">
            <?= $this->layout()->content; ?>
            <hr>
            <footer>
                <p>&copy; 2018 - <?= date('Y') ?> Desarrollado por Atijaguar Cía. Ltda.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
