<?php
return [
    'service_manager' => [
        'factories' => [
            \Seguridad\V1\Rest\Trusua\TrusuaResource::class => \Seguridad\V1\Rest\Trusua\TrusuaResourceFactory::class,
            \Seguridad\V1\Rest\Trperf\TrperfResource::class => \Seguridad\V1\Rest\Trperf\TrperfResourceFactory::class,
            \Seguridad\V1\Rest\Trmodl\TrmodlResource::class => \Seguridad\V1\Rest\Trmodl\TrmodlResourceFactory::class,
            \Seguridad\V1\Rest\Trcias\TrciasResource::class => \Seguridad\V1\Rest\Trcias\TrciasResourceFactory::class,
            \Seguridad\V1\Rest\Trappm\TrappmResource::class => \Seguridad\V1\Rest\Trappm\TrappmResourceFactory::class,
            \Seguridad\V1\Rest\Trayud\TrayudResource::class => \Seguridad\V1\Rest\Trayud\TrayudResourceFactory::class,
            \Seguridad\V1\Rest\Trayuh\TrayuhResource::class => \Seguridad\V1\Rest\Trayuh\TrayuhResourceFactory::class,
            \Seguridad\V1\Rest\Trcosi\TrcosiResource::class => \Seguridad\V1\Rest\Trcosi\TrcosiResourceFactory::class,
            \Seguridad\V1\Rest\Trdepr\TrdeprResource::class => \Seguridad\V1\Rest\Trdepr\TrdeprResourceFactory::class,
            \Seguridad\V1\Rest\Trdife\TrdifeResource::class => \Seguridad\V1\Rest\Trdife\TrdifeResourceFactory::class,
            \Seguridad\V1\Rest\Trdipo\TrdipoResource::class => \Seguridad\V1\Rest\Trdipo\TrdipoResourceFactory::class,
            \Seguridad\V1\Rest\Tresod\TresodResource::class => \Seguridad\V1\Rest\Tresod\TresodResourceFactory::class,
            \Seguridad\V1\Rest\Tresoh\TresohResource::class => \Seguridad\V1\Rest\Tresoh\TresohResourceFactory::class,
            \Seguridad\V1\Rest\Trhcos\TrhcosResource::class => \Seguridad\V1\Rest\Trhcos\TrhcosResourceFactory::class,
            \Seguridad\V1\Rest\Trhpad\TrhpadResource::class => \Seguridad\V1\Rest\Trhpad\TrhpadResourceFactory::class,
            \Seguridad\V1\Rest\Trhpah\TrhpahResource::class => \Seguridad\V1\Rest\Trhpah\TrhpahResourceFactory::class,
            \Seguridad\V1\Rest\Trhpam\TrhpamResource::class => \Seguridad\V1\Rest\Trhpam\TrhpamResourceFactory::class,
            \Seguridad\V1\Rest\Trmset\TrmsetResource::class => \Seguridad\V1\Rest\Trmset\TrmsetResourceFactory::class,
            \Seguridad\V1\Rest\Trmsus\TrmsusResource::class => \Seguridad\V1\Rest\Trmsus\TrmsusResourceFactory::class,
            \Seguridad\V1\Rest\Tropcd\TropcdResource::class => \Seguridad\V1\Rest\Tropcd\TropcdResourceFactory::class,
            \Seguridad\V1\Rest\Tropch\TropchResource::class => \Seguridad\V1\Rest\Tropch\TropchResourceFactory::class,
            \Seguridad\V1\Rest\Trperd\TrperdResource::class => \Seguridad\V1\Rest\Trperd\TrperdResourceFactory::class,
            \Seguridad\V1\Rest\Trpref\TrprefResource::class => \Seguridad\V1\Rest\Trpref\TrprefResourceFactory::class,
            \Seguridad\V1\Rest\Trpriv\TrprivResource::class => \Seguridad\V1\Rest\Trpriv\TrprivResourceFactory::class,
            \Seguridad\V1\Rest\Trreer\TrreerResource::class => \Seguridad\V1\Rest\Trreer\TrreerResourceFactory::class,
            \Seguridad\V1\Rest\Trtabd\TrtabdResource::class => \Seguridad\V1\Rest\Trtabd\TrtabdResourceFactory::class,
            \Seguridad\V1\Rest\Trtabh\TrtabhResource::class => \Seguridad\V1\Rest\Trtabh\TrtabhResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'seguridad.rest.trusua' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trusua[/:trusua_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trusua\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trperf' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trperf[/:trperf_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trperf\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trmodl' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trmodl[/:trmodl_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trmodl\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trcias' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trcias[/:trcias_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trcias\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trappm' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trappm[/:trappm_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trappm\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trayud' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trayud[/:trayud_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trayud\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trayuh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trayuh[/:trayuh_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trayuh\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trcosi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trcosi[/:trcosi_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trcosi\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trdepr' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trdepr[/:trdepr_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trdepr\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trdife' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trdife[/:trdife_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trdife\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trdipo' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trdipo[/:trdipo_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trdipo\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.tresod' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tresod[/:tresod_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Tresod\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.tresoh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tresoh[/:tresoh_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Tresoh\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trhcos' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trhcos[/:trhcos_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trhcos\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trhpad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trhpad[/:trhpad_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trhpad\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trhpah' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trhpah[/:trhpah_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trhpah\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trhpam' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trhpam[/:trhpam_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trhpam\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trmset' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trmset[/:trmset_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trmset\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trmsus' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trmsus[/:trmsus_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trmsus\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.tropcd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tropcd[/:tropcd_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Tropcd\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.tropch' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tropch[/:tropch_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Tropch\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trperd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trperd[/:trperd_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trperd\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trpref' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trpref[/:trpref_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trpref\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trpriv' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trpriv[/:trpriv_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trpriv\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trreer' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trreer[/:trreer_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trreer\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trtabd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trtabd[/:trtabd_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trtabd\\Controller',
                    ],
                ],
            ],
            'seguridad.rest.trtabh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/trtabh[/:trtabh_id]',
                    'defaults' => [
                        'controller' => 'Seguridad\\V1\\Rest\\Trtabh\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'seguridad.rest.trusua',
            1 => 'seguridad.rest.trperf',
            4 => 'seguridad.rest.trmodl',
            5 => 'seguridad.rest.trcias',
            6 => 'seguridad.rest.trappm',
            7 => 'seguridad.rest.trayud',
            8 => 'seguridad.rest.trayuh',
            9 => 'seguridad.rest.trcosi',
            10 => 'seguridad.rest.trdepr',
            11 => 'seguridad.rest.trdife',
            12 => 'seguridad.rest.trdipo',
            13 => 'seguridad.rest.tresod',
            14 => 'seguridad.rest.tresoh',
            15 => 'seguridad.rest.trhcos',
            16 => 'seguridad.rest.trhpad',
            17 => 'seguridad.rest.trhpah',
            18 => 'seguridad.rest.trhpam',
            19 => 'seguridad.rest.trmset',
            20 => 'seguridad.rest.trmsus',
            21 => 'seguridad.rest.tropcd',
            22 => 'seguridad.rest.tropch',
            23 => 'seguridad.rest.trperd',
            24 => 'seguridad.rest.trpref',
            25 => 'seguridad.rest.trpriv',
            26 => 'seguridad.rest.trreer',
            27 => 'seguridad.rest.trtabd',
            28 => 'seguridad.rest.trtabh',
        ],
    ],
    'zf-rest' => [
        'Seguridad\\V1\\Rest\\Trusua\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trusua\TrusuaResource::class,
            'route_name' => 'seguridad.rest.trusua',
            'route_identifier_name' => 'trusua_id',
            'collection_name' => 'trusua',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trusua\TrusuaEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trusua\TrusuaCollection::class,
            'service_name' => 'Trusua',
        ],
        'Seguridad\\V1\\Rest\\Trperf\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trperf\TrperfResource::class,
            'route_name' => 'seguridad.rest.trperf',
            'route_identifier_name' => 'trperf_id',
            'collection_name' => 'trperf',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trperf\TrperfEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trperf\TrperfCollection::class,
            'service_name' => 'Trperf',
        ],
        'Seguridad\\V1\\Rest\\Trmodl\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trmodl\TrmodlResource::class,
            'route_name' => 'seguridad.rest.trmodl',
            'route_identifier_name' => 'trmodl_id',
            'collection_name' => 'trmodl',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trmodl\TrmodlEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trmodl\TrmodlCollection::class,
            'service_name' => 'Trmodl',
        ],
        'Seguridad\\V1\\Rest\\Trcias\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trcias\TrciasResource::class,
            'route_name' => 'seguridad.rest.trcias',
            'route_identifier_name' => 'trcias_id',
            'collection_name' => 'trcias',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trcias\TrciasEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trcias\TrciasCollection::class,
            'service_name' => 'Trcias',
        ],
        'Seguridad\\V1\\Rest\\Trappm\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trappm\TrappmResource::class,
            'route_name' => 'seguridad.rest.trappm',
            'route_identifier_name' => 'trappm_id',
            'collection_name' => 'trappm',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trappm\TrappmEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trappm\TrappmCollection::class,
            'service_name' => 'Trappm',
        ],
        'Seguridad\\V1\\Rest\\Trayud\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trayud\TrayudResource::class,
            'route_name' => 'seguridad.rest.trayud',
            'route_identifier_name' => 'trayud_id',
            'collection_name' => 'trayud',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trayud\TrayudEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trayud\TrayudCollection::class,
            'service_name' => 'Trayud',
        ],
        'Seguridad\\V1\\Rest\\Trayuh\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trayuh\TrayuhResource::class,
            'route_name' => 'seguridad.rest.trayuh',
            'route_identifier_name' => 'trayuh_id',
            'collection_name' => 'trayuh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trayuh\TrayuhEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trayuh\TrayuhCollection::class,
            'service_name' => 'Trayuh',
        ],
        'Seguridad\\V1\\Rest\\Trcosi\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trcosi\TrcosiResource::class,
            'route_name' => 'seguridad.rest.trcosi',
            'route_identifier_name' => 'trcosi_id',
            'collection_name' => 'trcosi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trcosi\TrcosiEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trcosi\TrcosiCollection::class,
            'service_name' => 'Trcosi',
        ],
        'Seguridad\\V1\\Rest\\Trdepr\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trdepr\TrdeprResource::class,
            'route_name' => 'seguridad.rest.trdepr',
            'route_identifier_name' => 'trdepr_id',
            'collection_name' => 'trdepr',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trdepr\TrdeprEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trdepr\TrdeprCollection::class,
            'service_name' => 'Trdepr',
        ],
        'Seguridad\\V1\\Rest\\Trdife\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trdife\TrdifeResource::class,
            'route_name' => 'seguridad.rest.trdife',
            'route_identifier_name' => 'trdife_id',
            'collection_name' => 'trdife',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trdife\TrdifeEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trdife\TrdifeCollection::class,
            'service_name' => 'Trdife',
        ],
        'Seguridad\\V1\\Rest\\Trdipo\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trdipo\TrdipoResource::class,
            'route_name' => 'seguridad.rest.trdipo',
            'route_identifier_name' => 'trdipo_id',
            'collection_name' => 'trdipo',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trdipo\TrdipoEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trdipo\TrdipoCollection::class,
            'service_name' => 'Trdipo',
        ],
        'Seguridad\\V1\\Rest\\Tresod\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Tresod\TresodResource::class,
            'route_name' => 'seguridad.rest.tresod',
            'route_identifier_name' => 'tresod_id',
            'collection_name' => 'tresod',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Tresod\TresodEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Tresod\TresodCollection::class,
            'service_name' => 'Tresod',
        ],
        'Seguridad\\V1\\Rest\\Tresoh\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Tresoh\TresohResource::class,
            'route_name' => 'seguridad.rest.tresoh',
            'route_identifier_name' => 'tresoh_id',
            'collection_name' => 'tresoh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Tresoh\TresohEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Tresoh\TresohCollection::class,
            'service_name' => 'Tresoh',
        ],
        'Seguridad\\V1\\Rest\\Trhcos\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trhcos\TrhcosResource::class,
            'route_name' => 'seguridad.rest.trhcos',
            'route_identifier_name' => 'trhcos_id',
            'collection_name' => 'trhcos',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trhcos\TrhcosEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trhcos\TrhcosCollection::class,
            'service_name' => 'Trhcos',
        ],
        'Seguridad\\V1\\Rest\\Trhpad\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trhpad\TrhpadResource::class,
            'route_name' => 'seguridad.rest.trhpad',
            'route_identifier_name' => 'trhpad_id',
            'collection_name' => 'trhpad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trhpad\TrhpadEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trhpad\TrhpadCollection::class,
            'service_name' => 'Trhpad',
        ],
        'Seguridad\\V1\\Rest\\Trhpah\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trhpah\TrhpahResource::class,
            'route_name' => 'seguridad.rest.trhpah',
            'route_identifier_name' => 'trhpah_id',
            'collection_name' => 'trhpah',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trhpah\TrhpahEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trhpah\TrhpahCollection::class,
            'service_name' => 'Trhpah',
        ],
        'Seguridad\\V1\\Rest\\Trhpam\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trhpam\TrhpamResource::class,
            'route_name' => 'seguridad.rest.trhpam',
            'route_identifier_name' => 'trhpam_id',
            'collection_name' => 'trhpam',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trhpam\TrhpamEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trhpam\TrhpamCollection::class,
            'service_name' => 'Trhpam',
        ],
        'Seguridad\\V1\\Rest\\Trmset\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trmset\TrmsetResource::class,
            'route_name' => 'seguridad.rest.trmset',
            'route_identifier_name' => 'trmset_id',
            'collection_name' => 'trmset',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trmset\TrmsetEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trmset\TrmsetCollection::class,
            'service_name' => 'Trmset',
        ],
        'Seguridad\\V1\\Rest\\Trmsus\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trmsus\TrmsusResource::class,
            'route_name' => 'seguridad.rest.trmsus',
            'route_identifier_name' => 'trmsus_id',
            'collection_name' => 'trmsus',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trmsus\TrmsusEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trmsus\TrmsusCollection::class,
            'service_name' => 'Trmsus',
        ],
        'Seguridad\\V1\\Rest\\Tropcd\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Tropcd\TropcdResource::class,
            'route_name' => 'seguridad.rest.tropcd',
            'route_identifier_name' => 'tropcd_id',
            'collection_name' => 'tropcd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Tropcd\TropcdEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Tropcd\TropcdCollection::class,
            'service_name' => 'Tropcd',
        ],
        'Seguridad\\V1\\Rest\\Tropch\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Tropch\TropchResource::class,
            'route_name' => 'seguridad.rest.tropch',
            'route_identifier_name' => 'tropch_id',
            'collection_name' => 'tropch',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Tropch\TropchEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Tropch\TropchCollection::class,
            'service_name' => 'Tropch',
        ],
        'Seguridad\\V1\\Rest\\Trperd\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trperd\TrperdResource::class,
            'route_name' => 'seguridad.rest.trperd',
            'route_identifier_name' => 'trperd_id',
            'collection_name' => 'trperd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trperd\TrperdEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trperd\TrperdCollection::class,
            'service_name' => 'Trperd',
        ],
        'Seguridad\\V1\\Rest\\Trpref\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trpref\TrprefResource::class,
            'route_name' => 'seguridad.rest.trpref',
            'route_identifier_name' => 'trpref_id',
            'collection_name' => 'trpref',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trpref\TrprefEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trpref\TrprefCollection::class,
            'service_name' => 'Trpref',
        ],
        'Seguridad\\V1\\Rest\\Trpriv\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trpriv\TrprivResource::class,
            'route_name' => 'seguridad.rest.trpriv',
            'route_identifier_name' => 'trpriv_id',
            'collection_name' => 'trpriv',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trpriv\TrprivEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trpriv\TrprivCollection::class,
            'service_name' => 'Trpriv',
        ],
        'Seguridad\\V1\\Rest\\Trreer\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trreer\TrreerResource::class,
            'route_name' => 'seguridad.rest.trreer',
            'route_identifier_name' => 'trreer_id',
            'collection_name' => 'trreer',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trreer\TrreerEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trreer\TrreerCollection::class,
            'service_name' => 'Trreer',
        ],
        'Seguridad\\V1\\Rest\\Trtabd\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trtabd\TrtabdResource::class,
            'route_name' => 'seguridad.rest.trtabd',
            'route_identifier_name' => 'trtabd_id',
            'collection_name' => 'trtabd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trtabd\TrtabdEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trtabd\TrtabdCollection::class,
            'service_name' => 'Trtabd',
        ],
        'Seguridad\\V1\\Rest\\Trtabh\\Controller' => [
            'listener' => \Seguridad\V1\Rest\Trtabh\TrtabhResource::class,
            'route_name' => 'seguridad.rest.trtabh',
            'route_identifier_name' => 'trtabh_id',
            'collection_name' => 'trtabh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Seguridad\V1\Rest\Trtabh\TrtabhEntity::class,
            'collection_class' => \Seguridad\V1\Rest\Trtabh\TrtabhCollection::class,
            'service_name' => 'Trtabh',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'Seguridad\\V1\\Rest\\Trusua\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trperf\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trmodl\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trcias\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trappm\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trayud\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trayuh\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trcosi\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trdepr\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trdife\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trdipo\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Tresod\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Tresoh\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trhcos\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trhpad\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trhpah\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trhpam\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trmset\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trmsus\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Tropcd\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Tropch\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trperd\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trpref\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trpriv\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trreer\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trtabd\\Controller' => 'HalJson',
            'Seguridad\\V1\\Rest\\Trtabh\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'Seguridad\\V1\\Rest\\Trusua\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trperf\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trmodl\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trcias\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trappm\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trayud\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trayuh\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trcosi\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trdepr\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trdife\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trdipo\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tresod\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tresoh\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhcos\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhpad\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhpah\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhpam\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trmset\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trmsus\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tropcd\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tropch\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trperd\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trpref\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trpriv\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trreer\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trtabd\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trtabh\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Seguridad\\V1\\Rest\\Trusua\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trperf\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trmodl\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trcias\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trappm\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trayud\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trayuh\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trcosi\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trdepr\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trdife\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trdipo\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tresod\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tresoh\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhcos\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhpad\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhpah\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trhpam\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trmset\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trmsus\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tropcd\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Tropch\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trperd\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trpref\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trpriv\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trreer\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trtabd\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
            'Seguridad\\V1\\Rest\\Trtabh\\Controller' => [
                0 => 'application/vnd.seguridad.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \Seguridad\V1\Rest\Trusua\TrusuaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trusua',
                'route_identifier_name' => 'trusua_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trusua\TrusuaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trusua',
                'route_identifier_name' => 'trusua_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trperf\TrperfEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trperf',
                'route_identifier_name' => 'trperf_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trperf\TrperfCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trperf',
                'route_identifier_name' => 'trperf_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trmodl\TrmodlEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trmodl',
                'route_identifier_name' => 'trmodl_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trmodl\TrmodlCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trmodl',
                'route_identifier_name' => 'trmodl_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trcias\TrciasEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trcias',
                'route_identifier_name' => 'trcias_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trcias\TrciasCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trcias',
                'route_identifier_name' => 'trcias_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trappm\TrappmEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trappm',
                'route_identifier_name' => 'trappm_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trappm\TrappmCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trappm',
                'route_identifier_name' => 'trappm_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trayud\TrayudEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trayud',
                'route_identifier_name' => 'trayud_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trayud\TrayudCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trayud',
                'route_identifier_name' => 'trayud_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trayuh\TrayuhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trayuh',
                'route_identifier_name' => 'trayuh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trayuh\TrayuhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trayuh',
                'route_identifier_name' => 'trayuh_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trcosi\TrcosiEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trcosi',
                'route_identifier_name' => 'trcosi_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trcosi\TrcosiCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trcosi',
                'route_identifier_name' => 'trcosi_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trdepr\TrdeprEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trdepr',
                'route_identifier_name' => 'trdepr_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trdepr\TrdeprCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trdepr',
                'route_identifier_name' => 'trdepr_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trdife\TrdifeEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trdife',
                'route_identifier_name' => 'trdife_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trdife\TrdifeCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trdife',
                'route_identifier_name' => 'trdife_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trdipo\TrdipoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trdipo',
                'route_identifier_name' => 'trdipo_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trdipo\TrdipoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trdipo',
                'route_identifier_name' => 'trdipo_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Tresod\TresodEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tresod',
                'route_identifier_name' => 'tresod_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Tresod\TresodCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tresod',
                'route_identifier_name' => 'tresod_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Tresoh\TresohEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tresoh',
                'route_identifier_name' => 'tresoh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Tresoh\TresohCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tresoh',
                'route_identifier_name' => 'tresoh_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trhcos\TrhcosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhcos',
                'route_identifier_name' => 'trhcos_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trhcos\TrhcosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhcos',
                'route_identifier_name' => 'trhcos_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trhpad\TrhpadEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhpad',
                'route_identifier_name' => 'trhpad_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trhpad\TrhpadCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhpad',
                'route_identifier_name' => 'trhpad_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trhpah\TrhpahEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhpah',
                'route_identifier_name' => 'trhpah_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trhpah\TrhpahCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhpah',
                'route_identifier_name' => 'trhpah_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trhpam\TrhpamEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhpam',
                'route_identifier_name' => 'trhpam_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trhpam\TrhpamCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trhpam',
                'route_identifier_name' => 'trhpam_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trmset\TrmsetEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trmset',
                'route_identifier_name' => 'trmset_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trmset\TrmsetCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trmset',
                'route_identifier_name' => 'trmset_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trmsus\TrmsusEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trmsus',
                'route_identifier_name' => 'trmsus_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trmsus\TrmsusCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trmsus',
                'route_identifier_name' => 'trmsus_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Tropcd\TropcdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tropcd',
                'route_identifier_name' => 'tropcd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Tropcd\TropcdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tropcd',
                'route_identifier_name' => 'tropcd_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Tropch\TropchEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tropch',
                'route_identifier_name' => 'tropch_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Tropch\TropchCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.tropch',
                'route_identifier_name' => 'tropch_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trperd\TrperdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trperd',
                'route_identifier_name' => 'trperd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trperd\TrperdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trperd',
                'route_identifier_name' => 'trperd_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trpref\TrprefEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trpref',
                'route_identifier_name' => 'trpref_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trpref\TrprefCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trpref',
                'route_identifier_name' => 'trpref_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trpriv\TrprivEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trpriv',
                'route_identifier_name' => 'trpriv_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trpriv\TrprivCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trpriv',
                'route_identifier_name' => 'trpriv_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trreer\TrreerEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trreer',
                'route_identifier_name' => 'trreer_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trreer\TrreerCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trreer',
                'route_identifier_name' => 'trreer_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trtabd\TrtabdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trtabd',
                'route_identifier_name' => 'trtabd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trtabd\TrtabdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trtabd',
                'route_identifier_name' => 'trtabd_id',
                'is_collection' => true,
            ],
            \Seguridad\V1\Rest\Trtabh\TrtabhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trtabh',
                'route_identifier_name' => 'trtabh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Seguridad\V1\Rest\Trtabh\TrtabhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'seguridad.rest.trtabh',
                'route_identifier_name' => 'trtabh_id',
                'is_collection' => true,
            ],
        ],
    ],
];
